version: "3.9"
services:
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    volumes:
      - ./persistencia:/data/db
    ports: 
      - "27017:27017"
    networks:
      - red-db

  server1:
    image: pabloandresarg/server:latest
    ports:
     - "3000"
    depends_on:
     - mongo
    environment:
    - PORT=3001
    - ATENDIO=201800464
    networks:
      - red-servidores
      - red-db

  server2:
    image: pabloandresarg/server:latest
    ports:
     - "3000"
    depends_on:
     - mongo
    environment:
    - PORT=3002
    - ATENDIO=201503798
    networks:
 
      - red-servidores
      - red-db

  server3:
    image: pabloandresarg/server:latest
    ports:
     - "3000"
    depends_on:
     - mongo
    environment:
    - PORT=3003
    - ATENDIO=201113915
    networks:
      - red-servidores
      - red-db
  frontend:
    image: pabloandresarg/front:latest
    ports:
     - "80:80"
    networks:
    
      - red-servidores

      - red-frontend
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - server1
      - server2
      - server3

    ports:
      - "4500:4500"
    networks:
      - red-servidores

networks:

  red-frontend:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.55.0/24
        - gateway: 192.168.55.1

  red-servidores:
    driver: bridge
    ipam:
      config:
        - subnet: 172.35.75.0/24
        - gateway: 172.35.75.1

  red-db:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.15.0/24
        - gateway: 10.10.15.1
